### ISSUE TITLE
 the publishWithContext interface will not return when it times out

### ISSUE THREAD

**Issue by liuxiaomeiG** [rabbitmq/amqp091-go#178]
When there is a memory alarm in the rabbit, the publishWithContext interface will not return when it times out, and will be stuck all the time. In addition, you cannot manually close the channel and connection at this time

**Comment by Zerpet** [comment]
This happens because rabbitmq stops reading from the connection socket when there's a memory alarm; therefore, the I/O call to write the publish frame to the socket never returns. Unfortunately, the [io.Writer](https://pkg.go.dev/io#Writer) does not provide a way to pass down the context. In summary, if the library is waiting on a blocking I/O operation, the context cancellation is ignored.

The same applies to `Channel.Close` and `Connection.Close`. Those methods write a frame to the socket to communicate the server a clean channel/connection shutdown. That is how the [AMQP 0.9.1 Spec defines](https://rabbitmq.com/amqp-0-9-1-reference.html#connection.close) the `Close` method.

We could add an extension to the protocol, and provide `Connection.ForceClose(error)` function to forcibly close the underlying TCP connection and return immediately. However, I'm not sure how a forceful connection closure would help in this situation. RabbitMQ won't read anything from the connection until the memory alarm is cleared, and for the memory alarm to clear, usually is a matter of consumer apps consuming some messages.

**Comment by lukebakken** [comment]
Missed heartbeats should eventually close the connection, right?

**Comment by lukebakken** [comment]
So we can read from the socket just fine, not write to it.

**Comment by lukebakken** [comment]
It looks like we don't continue to set any deadlines after the connection is initialized. My understanding (after reading the docs briefly) is that prior to each write a deadline should be set for the write to complete. If the deadline passes, the blocking operation will throw an exception.

**Comment by Zerpet** [comment]
Indeed we don't set deadlines. It's a but tricky to do because a connection can have multiple channels, and if we set deadlines on each I/O operation on every channel, deadlines will overlap, because the deadline is set in the TCP connection i.e. in the `net.Conn` object returned in `Dial`. I think a safe compromise would be to set and renew an I/O deadline in the heartbeater.

**Comment by Zerpet** [comment]
hey everyone 👋 I have a test to reproduce this issue. However, I was slightly wrong about the heartbeater. Even when the connection is blocked (because memory alarm), the heartbeater keeps sending and receiving heartbeats. I verified that heartbeats keep flowing via WireShark and a network traffic capture. 

The problem is that `Channel.Close` and `Connection.Close` try to do a graceful shutdown by sending a `close` frame to the server. Since the connection is blocked, the server does not read this frame, and the calls to `Close()` never return.

I'd like to verify what happens in other clients, so that we take a consistent solution across our client implementations.

**Comment by lukebakken** [comment]
I'm pretty sure in this case the .NET client will throw on operation timeout exception.

**Comment by Zerpet** [comment]
@liuxiaomeiG we introduced a new function `Connection.CloseDeadline()`, which accepts a `time.Time` type parameter to set a deadline to close the connection. I hope this helps your app to not block during a memory alarm. 

Regarding `publishWithContext`, this function is expected to block on I/O during a memory alarm. It will unblock once the memory alarm is cleared. I understand this can be counter-intuitive, given that the function accepts a `context.Context` and it is expected to observe context cancellation. However, the problem is not related to context cancellation, but blocking I/O.
