### ISSUE TITLE
Exception (540) Reason: "NOT_IMPLEMENTED - prefetch_size!=0 

### ISSUE THREAD

**Issue by lyf571321556** [rabbitmq/amqp091-go#187]
### Describe the bug

Exception (540) Reason: "NOT_IMPLEMENTED - prefetch_size!=0 

### Reproduction steps

channel.Qos(1, 1, false)

### Expected behavior

support prefetchCount

**Comment by Zerpet** [comment]
It's not implemented in RabbitMQ server, and that's the message you are getting. We don't see value in supporting a prefetch size. Message sizes can vary, and if you happen to have a low prefetch size, consumers would be starved, since delivery is not possible.

To be clear: **prefetch count** is supported, prefetch size is not.

We will change this function in a future release to stop accepting `prefetchSize` as argument, and always send `0`
