### ISSUE TITLE
Support auto-reconnect and cluster

### ISSUE THREAD

**Issue by caevv** [rabbitmq/amqp091-go#65]
https://github.com/sirius1024/go-amqp-reconnect

**Comment by DanielePalaia** [comment]
Hi @caevv 

Thanks for the link.
We know that there are also other libraries wrapping this one in order to implement auto-reconnection.

But as stated in the documentation the reconnection support is not one of the goal of the library.
We may decide to create some example on how to implement this like in https://github.com/rabbitmq/amqp091-go/issues/40 but it is not one of the priority.
